# Generated by Django 4.2.10 on 2024-03-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0018_rename_name_place_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='label',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
